# Generated by Django 4.2 on 2025-01-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdbfilm',
            name='duration',
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
