# Generated by Django 4.2 on 2025-01-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imdbfilm_duration_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwebfilm',
            name='id_film',
            field=models.OneToOneField(db_column='id_film', on_delete=django.db.models.deletion.CASCADE, related_name='filmweb_film', to='api.film'),
        ),
        migrations.AlterField(
            model_name='imdbfilm',
            name='id_film',
            field=models.OneToOneField(db_column='id_film', on_delete=django.db.models.deletion.CASCADE, related_name='imdb_film', to='api.film'),
        ),
        migrations.AlterField(
            model_name='rottenfilm',
            name='id_film',
            field=models.OneToOneField(db_column='id_film', on_delete=django.db.models.deletion.CASCADE, related_name='rotten_film', to='api.film'),
        ),
    ]
