# Generated by Django 4.2 on 2025-01-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_filmwebfilm_id_film_alter_imdbfilm_id_film_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedFilms',
            fields=[
                ('id_film', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('critics_score', models.IntegerField()),
                ('user_score', models.IntegerField()),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'combinedfilms',
                'managed': False,
            },
        ),
    ]
