# Generated by Django 4.2 on 2025-01-28 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_combinedfilms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFilms',
            fields=[
                ('id_favourite', models.AutoField(primary_key=True, serialize=False)),
                ('id_film', models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_entries', to='api.film')),
                ('id_user', models.ForeignKey(db_column='id_system_user', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_films', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
